#! /bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
PARENT_DIR=$(dirname "$SCRIPT_DIR")
cd $PARENT_DIR

if  [[ ! -e output/summary ]]; then
    echo "Unable to find output directory!"
    exit -1
fi

find output/summary -iname "*.txt" | sort > misc/summary_files.txt

echo -e "\n\n"
echo "-----------------------------------------------"
echo "Extracting running times into misc/results.csv"
scripts/extract_running_time.jl


echo "-----------------------------------------------"
echo "Extracting all info into misc/extracted_date.csv"
scripts/extract_stats.jl

echo -e "\n\n"
echo "-----------------------------------------------"
echo "Generating plots... (patience)"
scripts/log_fit.jl


echo "-----------------------------------------------"
echo "Generating even more plots... (even more patience)"
scripts/plots.jl


echo "-----------------------------------------------"
echo "Generating table"
scripts/generate_table.jl >& misc/rt_table.tex

echo -e "\n\n"
echo "-----------------------------------------------"
echo "Generated:"
echo "        plots/rt_fit.pdf"
echo "-----------------------------------------------"


DPAPER=~/papers/26/k_grid_points/figs/
cp plots/rt_fit.pdf  $DPAPER
cp misc/rt_table.tex $DPAPER

cp plots/configs_computed.pdf     $DPAPER
cp plots/longest_edge_len.pdf     $DPAPER
cp plots/boundary_grid_points.pdf $DPAPER
cp plots/vertices.pdf             $DPAPER


echo "-----------------------------------------------"
echo "Copied to $DPAPER"

